### PR TITLE
[Draft] Skeleton of riscv64 jit filles based on mips64

### PR DESCRIPTION
**Pull request by ninja3011**
A lot of code is still based on mips64 files, will continually replace the functions and architecture for riscv64. (Ongoing Work)

### CODE REVIEW

**Comment by dhairyashah1** [comment]
On based on a comparative study of `riscv64` and `mips64` register architectures, the following changes were made:
1. necessary base and floating point registers for riscv64 were defined
2. accordingly, essential classes, methods, and instances were re-modeled for `riscv64`

Working on:
1. perfecting the backbone behind JIT interpretation and compilation flow for a successful build and regression tests on `riscv64`

**Comment by dhairyashah1** [comment]
1. Added run.sh shell script for creating build environment for spidermonkey build (debug and optimised)
2. In ` js/src/jit/riscv64/Simulator-riscv64.cpp `
        a. Added RISC-V Arithmetic and Logical Instructions List 
        b. Compared it with MIPS64 architecture instructions
        c. Added comments
3. To add:
        a. Case logic of added instructions
        b. Global listing of these instructions as per immediate or register type

**Comment by dhairyashah1** [comment]
1. Studied MIPS64 and RISCV architecture Instructions and differences between them.
2. Added RISC-V compatible Instruction Definitions for previously listed Instructions.
3. Following Instructions are added in `js/src/jit/riscv64/Simulator-riscv64.cpp ` and defined for RV64GC:
       a. Immediate Arithmetic Instructions(Addition and Subtraction)
       b. Base Memory Instructions
4. Todo:
       a. Define other RiSCV Instructions 
       b.  Test the code (Limitation: Regression Testing requires built RISCV Binaries, currently both native and cross-compile build produce build errors - [Issues](https://github.com/plctlab/gecko-dev-riscv/issues))

**Comment by luyahan** [comment]
too old

**Pull request closed without merging**
